/*  Chimaltenango 15 de Agosto del 2023
 *  Programador: Daniel Angel Ambrocio Coj
 *  Nombre de la Empresa: "Puzzle Haven"
 *  La empresa se dedica a la venta de rompecabezas
 *  Es el inicio de sesion de la empresa
 */
package principal;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class inicio extends javax.swing.JFrame {

    
    public inicio() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     *
     * @return
     */
    @Override
    public Image getIconImage() {

        Image retvalue;
        retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/cubo.JPG"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        women = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        userr = new javax.swing.JLabel();
        clave = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        iniciar = new javax.swing.JButton();
        salirt = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        women.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/womenx.jpg"))); // NOI18N
        getContentPane().add(women, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 560));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("PUZZLE HAVEN");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Iniciar Seción:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        userr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        userr.setForeground(new java.awt.Color(255, 255, 255));
        userr.setText("Usuario:");

        clave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        clave.setForeground(new java.awt.Color(255, 255, 255));
        clave.setText("Password:");

        pass.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clave)
                    .addComponent(userr))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(txtuser))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userr)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 520, 170));

        iniciar.setBackground(java.awt.Color.darkGray);
        iniciar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio .png"))); // NOI18N
        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 210, 80));

        salirt.setBackground(new java.awt.Color(0, 0, 0));
        salirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoxxxx.png"))); // NOI18N
        salirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirtActionPerformed(evt);
            }
        });
        getContentPane().add(salirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 70, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thumb-1920-483806.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirtActionPerformed

        System.exit(0);

    }//GEN-LAST:event_salirtActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        

        String user, pwd;

        user = txtuser.getText();
        pwd = pass.getText();

        if (user.equals("cubo") && pwd.equals("cubo2023")) {
            JOptionPane.showMessageDialog(null, " !Bienvenido! ");
            Ventana ven = new Ventana();
            ven.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o Password Incorrectas!!!");
        }


    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clave;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton salirt;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel userr;
    private javax.swing.JLabel women;
    // End of variables declaration//GEN-END:variables
}
