/*  Chimaltenango 15 de Agosto del 2023
 *  Programador: Daniel Angel Ambrocio Coj
 *  Nombre de la Empresa: "Puzzle Haven"
 *  La empresa se dedica a la venta de rompecabezas
 *  Sistema de la empresa con base de datos en SQL
 */
package principal;

import configuracion.conection;
import java.awt.Desktop;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public final class Ventana extends javax.swing.JFrame {

    conection con1 = new conection();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int ido;
    private TableRowSorter trsfiltro;
    String filtro;

    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        consultar();

    }

    /**
     *
     * @return
     */
    @Override
    public Image getIconImage() {

        Image retvalue;
        retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/cubo.JPG"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datos = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        ide = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        opciones = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        salir = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        busqueda = new javax.swing.JTextField();
        abirirmuser = new javax.swing.JButton();
        abirirmtec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datos.setBackground(java.awt.Color.darkGray);
        datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        ID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("Codigo Producto");

        ide.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        nombre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre Producto");

        nom.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio Unitario");

        precio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad Producto");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad de Uso");

        cantidad.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        edad.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(ID)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(57, 57, 57)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ide, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(precio)
                    .addComponent(nom)
                    .addComponent(cantidad)
                    .addComponent(edad))
                .addGap(27, 27, 27))
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addComponent(ide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 690, 406));

        opciones.setBackground(java.awt.Color.darkGray);
        opciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        opciones.setForeground(new java.awt.Color(255, 255, 255));

        agregar.setBackground(java.awt.Color.darkGray);
        agregar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setBackground(java.awt.Color.darkGray);
        modificar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edid.png"))); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setBackground(java.awt.Color.darkGray);
        eliminar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basura  (1).png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        nuevo.setBackground(java.awt.Color.darkGray);
        nuevo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpi.png"))); // NOI18N
        nuevo.setText("Limpiar");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informe inventario .png"))); // NOI18N
        jButton1.setText("Informe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesLayout = new javax.swing.GroupLayout(opciones);
        opciones.setLayout(opcionesLayout);
        opcionesLayout.setHorizontalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesLayout.createSequentialGroup()
                .addComponent(agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addContainerGap())
            .addGroup(opcionesLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(nuevo)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesLayout.setVerticalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 700, 290));

        bd.setBackground(java.awt.Color.darkGray);
        bd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Base de Datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        Tabla.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producto", "Nombre Producto", "Precio Unitario", "Cantidad Producto", "Edad de Uso"
            }
        ));
        Tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setMinWidth(90);
            Tabla.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        javax.swing.GroupLayout bdLayout = new javax.swing.GroupLayout(bd);
        bd.setLayout(bdLayout);
        bdLayout.setHorizontalGroup(
            bdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        bdLayout.setVerticalGroup(
            bdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 740, 580));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Puzzle Haven");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/talves .png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 120, 120));

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoxxxx.png"))); // NOI18N
        salir.setToolTipText("");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 0, 70, 30));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        buscar.setBackground(java.awt.Color.darkGray);
        buscar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mi dibujo (1)_1.png"))); // NOI18N
        buscar.setText("Nombre:");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        busqueda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        busqueda.setForeground(new java.awt.Color(0, 0, 0));
        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 730, 130));

        abirirmuser.setBackground(java.awt.Color.darkGray);
        abirirmuser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        abirirmuser.setForeground(new java.awt.Color(255, 255, 255));
        abirirmuser.setText("Manual de Usuario");
        abirirmuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abirirmuserActionPerformed(evt);
            }
        });
        getContentPane().add(abirirmuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 160, -1));

        abirirmtec.setBackground(java.awt.Color.darkGray);
        abirirmtec.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        abirirmtec.setForeground(new java.awt.Color(255, 255, 255));
        abirirmtec.setText("Manual Tecnico");
        getContentPane().add(abirirmtec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mi dibujo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondprincipal.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:

        agregar();
        consultar();
        nuevo();
    }//GEN-LAST:event_agregarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se selcciono la fila");

        } else {
            String codigo = (String) Tabla.getValueAt(fila, 0);
            String nombre = (String) Tabla.getValueAt(fila, 1);
            float pre = (float) Double.parseDouble((String) Tabla.getValueAt(fila, 2).toString());
            int canti = Integer.parseInt((String) Tabla.getValueAt(fila, 3).toString());
            String ed = (String) Tabla.getValueAt(fila, 4);

            ide.setText("" + codigo);
            nom.setText("" + nombre);
            precio.setText("" + pre);
            cantidad.setText("" + canti);
            edad.setText("" + ed);

        }

    }//GEN-LAST:event_TablaMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        modificar();
        consultar();
        nuevo();


    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:

        eliminar();
        consultar();
        nuevo();
    }//GEN-LAST:event_eliminarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        busqueda.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(final KeyEvent e) {

                String cadena = busqueda.getText();
                busqueda.setText(cadena);
                repaint();
                filtro();

            }

        });


    }//GEN-LAST:event_buscarActionPerformed

    private void busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyTyped
        // TODO add your handling code here:
        trsfiltro = new TableRowSorter(Tabla.getModel());
        Tabla.setRowSorter(trsfiltro);


    }//GEN-LAST:event_busquedaKeyTyped

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        doc();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void abirirmuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abirirmuserActionPerformed
        String filePath = "C:\\Users\\HYMA 57\\Documents\\NetBeansProjects\\Puzzle_Haven\\src\\manuales\\Manual de Usuario.pdf";

        File file = new File(filePath);

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.OPEN)) {
                    desktop.open(file);
                } else {
                    System.out.println("La acción OPEN no está soportada en este sistema.");
                }
            } else {
                System.out.println("El escritorio no está soportado en este sistema.");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_abirirmuserActionPerformed

    void doc() {
        String informeOrigen = "C:\\Users\\HYMA 57\\Documents\\NetBeansProjects\\Puzzle_Haven\\src\\principal\\informe.jrxml";

        try {
            //compilamos el archivo jrkml
            JasperReport jasperReport = JasperCompileManager.compileReport(informeOrigen);

            //crear informe
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conet);

            //System.out.println("Gennerando informe");
            // exportar el formato que se quiere del pdf
            JasperExportManager.exportReportToPdf(jasperPrint);

            // visualizar el archivo con JasperWiewer
            JasperViewer.viewReport(jasperPrint);

            // En caso de erro se nos mandara por consola
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "No se pudo generar el documento!!!");

        }

    }

    void filtro() {

        filtro = busqueda.getText();
        trsfiltro.setRowFilter(RowFilter.regexFilter(busqueda.getText(), 1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }

        });
    }

    void consultar() {
        String sql = "Select * from producto";

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] producto = new Object[5];
            modelo = (DefaultTableModel) Tabla.getModel();

            while (rs.next()) {
                producto[0] = rs.getString("Codigo_Producto");
                producto[1] = rs.getString("Nombre_Producto");
                producto[2] = rs.getFloat("Precio_Unitario");
                producto[3] = rs.getInt("Cantidad_Producto");
                producto[4] = rs.getString("Edad_de_Uso");

                modelo.addRow(producto);
            }
            Tabla.setModel(modelo);

        } catch (Exception e) {

        }

    }

    void agregar() {
        String codigo = ide.getText();
        String nombre = nom.getText();
        String pre = precio.getText();
        String canti = cantidad.getText();
        String ed = edad.getText();

        try {
            if (codigo.equals("") || nombre.equals("") || pre.equals("") || canti.equals("") || ed.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan Datos");
                limpiarTabla();

            } else {

                String sql = "insert into producto(Codigo_Producto,Nombre_Producto,Precio_Unitario,Cantidad_Producto,Edad_de_Uso) values ('" + codigo + "','" + nombre + "','" + pre + "','" + canti + "','" + ed + "')";

                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente!!");
                limpiarTabla();

            }

        } catch (Exception e) {

        }

    }

    void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;

        }

    }

    void modificar() {
        String codigo = ide.getText();
        String nombre = nom.getText();
        String pre = precio.getText();
        String canti = cantidad.getText();
        String ed = edad.getText();

        try {
            if (codigo.equals("") || nombre.equals("") || pre.equals("") || canti.equals("") || ed.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan Datos");
                limpiarTabla();

            } else {

                String sql = "Update producto set Codigo_Producto ='" + codigo + "',Nombre_Producto ='" + nombre + "',Precio_Unitario ='" + pre + "',Cantidad_Producto ='" + canti + "',Edad_de_Uso='" + ed + "' where Codigo_Producto =" + codigo;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos Modificados!!");
                limpiarTabla();

            }

        } catch (Exception e) {

        }

    }

    // utilizamos esta parte 
    void eliminar() {
        String codigo = ide.getText();

        int fila = Tabla.getSelectedRow();

        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Producto no Selecionado");
                limpiarTabla();

            } else {
                String sql = "delete from producto where Codigo_Producto=" + codigo;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                limpiarTabla();
            }

        } catch (Exception e) {
        }

    }

    void nuevo() {
        ide.setText("");
        nom.setText("");
        precio.setText("");
        cantidad.setText("");
        edad.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton abirirmtec;
    private javax.swing.JButton abirirmuser;
    private javax.swing.JButton agregar;
    private javax.swing.JPanel bd;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField cantidad;
    private javax.swing.JPanel datos;
    private javax.swing.JTextField edad;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField ide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JPanel opciones;
    private javax.swing.JTextField precio;
    private javax.swing.JToggleButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
